# This is a GitHub action to mirror this repository to another repository located at
# MilfordGCDBackup/THIS_REPOS_NAME
# Please note that the repository must already have been created for this action to work
# The value of GIT_PASSWORD must be set in this repo's secrets, and should be the password
# of the MilfordGCDBackup GitHub user.

name: mirror-repository
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: 'https://github.com/MilfordGCDBackup/mirror-test.git'
          GIT_USERNAME: MilfordGCDBackup
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
